"""Divergence analysis data model and formatting utilities.

Parses Claude's JSON response into typed DivergenceRecord objects.
Provides confidence tier classification and academic export formatters.
"""

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from urllib.parse import quote_plus


@dataclass
class Hypothesis:
    """A single ranked hypothesis for why a divergence exists."""
    type: str           # divergence_type string
    confidence: float   # 0.0 – 1.0
    explanation: str    # scholarly explanation


@dataclass
class DivergenceRecord:
    """One MT/LXX divergence with full scholarly analysis."""
    reference: str
    mt_word: str
    lxx_word: str
    divergence_type: str
    confidence: float
    hypotheses: list
    dss_witness: object   # str or None
    citations: list
    analysis_technical: str
    analysis_plain: str
    discovery_ready: bool = False


# ── Classification ─────────────────────────────────────────────────────────

def confidence_tier(score: float) -> str:
    """Return 'HIGH', 'MEDIUM', or 'LOW' for a confidence score."""
    if score >= 0.75:
        return 'HIGH'
    if score >= 0.45:
        return 'MEDIUM'
    return 'LOW'


# ── Parsing ────────────────────────────────────────────────────────────────

def parse_claude_response(data: dict, reference: str) -> list:
    """Parse Claude's JSON dict into a list of DivergenceRecord objects.

    Records are sorted by confidence descending (highest first).
    """
    records = []

    for div in data.get('divergences', []):
        hypotheses = [
            Hypothesis(
                type=h.get('type', ''),
                confidence=float(h.get('confidence', 0.0)),
                explanation=h.get('explanation', ''),
            )
            for h in div.get('hypotheses', [])
        ]
        records.append(DivergenceRecord(
            reference=reference,
            mt_word=div.get('mt_word', ''),
            lxx_word=div.get('lxx_word', ''),
            divergence_type=div.get('divergence_type', ''),
            confidence=float(div.get('confidence', 0.0)),
            hypotheses=hypotheses,
            dss_witness=div.get('dss_witness') or None,
            citations=div.get('citations', []),
            analysis_technical=div.get('analysis_technical', ''),
            analysis_plain=div.get('analysis_plain', ''),
            discovery_ready=bool(div.get('discovery_ready', False)),
        ))

    return sorted(records, key=lambda r: r.confidence, reverse=True)


# ── Export ─────────────────────────────────────────────────────────────────

def format_sbl_footnote(record: DivergenceRecord) -> str:
    """Format divergence as an SBL-style footnote string."""
    parts = [f'In {record.reference}, MT {record.mt_word} vs. LXX {record.lxx_word}.']

    if record.hypotheses:
        parts.append(record.hypotheses[0].explanation)

    if record.dss_witness:
        parts.append(f'DSS evidence: {record.dss_witness}.')

    if record.citations:
        parts.append(f'Cf. {"; ".join(record.citations)}.')

    ref_slug = record.reference.replace(' ', '+')
    parts.append(
        f'Generated by BibCrit (https://bibcrit.app/divergence?ref={ref_slug}), '
        f'powered by Anthropic Claude. Jossi Fresco, ORCID: 0009-0000-2026-0836.'
    )
    return ' '.join(parts)


def format_bibtex(record: DivergenceRecord, model_version: str = 'Claude') -> str:
    """Format divergence as a BibTeX @misc entry."""
    key = (
        record.reference
        .replace(' ', '')
        .replace(':', '_')
        .replace('.', '')
    ) + 'Divergence2026'
    ref_slug = record.reference.replace(' ', '+')
    return (
        f'@misc{{{key},\n'
        f'  author       = {{Fresco, Jossi}},\n'
        f'  orcid        = {{ORCID: 0009-0000-2026-0836}},\n'
        f'  title        = {{{{BibCrit MT/LXX Divergence analysis of {record.reference}}}}},\n'
        f'  year         = {{2026}},\n'
        f'  howpublished = {{\\url{{https://bibcrit.app/divergence?ref={ref_slug}}}}},\n'
        f'  note         = {{Powered by {model_version}}},\n'
        f'}}'
    )


def format_ris(record: DivergenceRecord, model_version: str = 'Claude') -> str:
    """Format divergence as a RIS entry (Zotero / Mendeley compatible)."""
    import datetime
    year = datetime.date.today().year
    ref_slug = quote_plus(record.reference)
    lines = [
        'TY  - ELEC',
        f'TI  - MT/LXX Divergence at {record.reference}: {record.mt_word} / {record.lxx_word}',
        'AU  - Fresco, Jossi',
        f'PY  - {year}',
        f'UR  - https://bibcrit.app/divergence?ref={ref_slug}',
        'PB  - BibCrit',
        'DB  - BibCrit Analysis Cache',
    ]
    if record.analysis_technical:
        lines.append(f'N1  - {record.analysis_technical}')
    if record.dss_witness:
        lines.append(f'N1  - DSS witness: {record.dss_witness}')
    if record.citations:
        lines.append(f'N1  - Cf. {"; ".join(record.citations)}')
    lines.append(f'N1  - Generated by {model_version}')
    lines.append('ER  - ')
    return '\r\n'.join(lines)


def format_tei(records: list, reference: str, model_version: str = 'Claude',
               cached_at: str = '') -> str:
    """Format divergence records as TEI XML critical apparatus."""
    import datetime
    date_str = cached_at[:10] if cached_at else str(datetime.date.today())
    ref_slug = quote_plus(reference)

    tei = ET.Element('TEI', xmlns='http://www.tei-c.org/ns/1.0')

    # teiHeader
    header = ET.SubElement(tei, 'teiHeader')
    file_desc = ET.SubElement(header, 'fileDesc')
    title_stmt = ET.SubElement(file_desc, 'titleStmt')
    title_el = ET.SubElement(title_stmt, 'title')
    title_el.text = f'MT/LXX Divergence Analysis: {reference}'
    resp = ET.SubElement(title_stmt, 'respStmt')
    resp_el = ET.SubElement(resp, 'resp')
    resp_el.text = 'AI-assisted analysis'
    name_el = ET.SubElement(resp, 'name')
    name_el.text = f'BibCrit ({model_version})'

    pub_stmt = ET.SubElement(file_desc, 'publicationStmt')
    pub_el = ET.SubElement(pub_stmt, 'publisher')
    pub_el.text = 'BibCrit'
    date_el = ET.SubElement(pub_stmt, 'date')
    date_el.text = date_str
    avail = ET.SubElement(pub_stmt, 'availability')
    lic = ET.SubElement(avail, 'licence',
                        target='https://creativecommons.org/licenses/by/4.0/')
    lic.text = 'CC-BY 4.0'
    id_no = ET.SubElement(pub_stmt, 'idno', type='URI')
    id_no.text = f'https://bibcrit.app/divergence?ref={ref_slug}'

    src_desc = ET.SubElement(file_desc, 'sourceDesc')
    p_el = ET.SubElement(src_desc, 'p')
    p_el.text = (
        'AI-generated critical apparatus comparing Masoretic Text (MT) '
        'and Septuagint (LXX). Witnesses: Leningrad Codex (ETCBC), '
        'STEPBible LXXM / Vaticanus (B).'
    )

    # text body
    text_el = ET.SubElement(tei, 'text')
    body = ET.SubElement(text_el, 'body')
    list_app = ET.SubElement(body, 'listApp')
    list_app.set('ana', reference)

    for i, rec in enumerate(records, 1):
        app = ET.SubElement(list_app, 'app', n=str(i),
                            type=rec.divergence_type or 'unclassified')
        lem = ET.SubElement(app, 'lem', wit='MT')
        lem.text = rec.mt_word
        rdg = ET.SubElement(app, 'rdg', wit='LXX')
        rdg.text = rec.lxx_word
        if rec.dss_witness:
            rdg_dss = ET.SubElement(app, 'rdg', wit='DSS')
            rdg_dss.text = rec.dss_witness
        if rec.analysis_technical:
            note = ET.SubElement(app, 'note', type='analysis')
            note.text = rec.analysis_technical
        conf_note = ET.SubElement(app, 'note', type='confidence')
        conf_note.text = str(round(rec.confidence, 2))
        if rec.hypotheses:
            h_note = ET.SubElement(app, 'note', type='hypothesis')
            h_note.text = rec.hypotheses[0].explanation

    ET.indent(tei, space='  ')
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(
        tei, encoding='unicode', xml_declaration=False
    )
